# Generated by Django 5.0.3 on 2024-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uesc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
