# Generated by Django 5.0.3 on 2024-03-22 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uesc_app", "0002_alter_resultado_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="obs",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultado",
            name="titulo",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
